### ISSUE TITLE
Start up Issue

### ISSUE THREAD

**Issue by tootyta** [titshacking/Nitro#1]
I keep getting this when I start it up http://prntscr.com/ej5ycy . This is my config
<nitro>
	<mysql>
		<host>127.0.0.1</host>
		<username>root</username>
		<password></password>
		<database>purecp</database>
	</mysql>
</nitro>

**Comment by widd** [comment]
Is there a password on the root user?

**Comment by tootyta** [comment]
Yeah, I saw. I set a password for root and boom! It worked xD

**Comment by titshacking** [comment]
This is a password issue, if you're not using a password, change the string in MySQL.pm to:

`Mojo::mysql->new('mysql://' . $strUsername .  '@' . $strHost . '/' . $strDatabase)`

from

`Mojo::mysql->new('mysql://' . $strUsername . ':' . $strPassword . '@' . $strHost . '/' . $strDatabase)`
