### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Rover656** [titshacking/Nitro#18]
Hi there, good job on the project.
I need some help with the login,
Basically the client connection is recognised but isn't returned by the server.
Help is gratefully appreciated, thanks in advance! Also, could it be an issue running on a Raspberry Pi type B?

**Comment by Rover656** [comment]
Here is the debug log:
`       ___  __   __
|\ | |  |  |__) /  \
| \| |  |  |  \ \__/

INFO - Successfully loaded configuration
INFO - Successfully loaded 96 Igloos
INFO - Successfully loaded 352 Stamps
INFO - Successfully loaded 87 Rooms
INFO - Successfully loaded 57 Game Rooms
INFO - Successfully loaded 1384 Furnitures
INFO - Successfully loaded 5098 Items
INFO - Successfully loaded 39 EPF Items
INFO - Successfully loaded 24 Floors
INFO - Successfully loaded 204 Postcards
INFO - Successfully connected to MySQL server
INFO - Successfully connected to the server
NOTICE - You may now login to the game!
DEBUG - Incoming data: <policy-file-request/>
DEBUG - Outgoing data: <cross-domain-policy><allow-access-from domain='*' to-ports='6112'/></cross-domain-policy>
DEBUG - Outgoing data: %xt%rp%-1%0%
DEBUG - Incoming data: <msg t='sys'><body action='verChk' r='0'><ver v='153' /></body></msg>
DEBUG - Outgoing data: <msg t='sys'><body action='apiOK' r='0'></body></msg>
DEBUG - Incoming data: %xt%s%u#gp%-1%0%
DEBUG - Incoming data: <msg t='sys'><body action='rndK' r='-1'></body></msg>
`

**Comment by Rover656** [comment]
[log.txt](https://github.com/titshacking/Nitro/files/870233/log.txt)

**Comment by titshacking** [comment]
Did you implement the cookies.zip in the client folder?

**Comment by Rover656** [comment]
I saw it, how do you use it?

**Comment by titshacking** [comment]
You extract it, add it in **/play/v2/client** and edit the url in the actionscript found in the **.fla** and republish the swf.

**Comment by Rover656** [comment]
ok gimme a sec...

**Comment by titshacking** [comment]
Oh and also clear the cache

**Comment by Rover656** [comment]
Ok, starting server now, thanks for responding so quick!

**Comment by Rover656** [comment]
I am having a few issues, i am just rebooting my Pi

**Comment by Rover656** [comment]
It isn't working, I'm not even getting those old messages now...

**Comment by Rover656** [comment]
New output now:
[log.txt](https://github.com/titshacking/Nitro/files/870258/log.txt)

**Comment by Rover656** [comment]
@titshacking I think it may be my media server, could you link me to one that works please?

**Comment by Rover656** [comment]
I fixed it, the server couldn't find my DB. Thank you for all the support, I am now starring and following the repo!
