### ISSUE TITLE
NOT AN ISSUE, JUST A FIX :p

### ISSUE THREAD

**Issue by tootyta** [titshacking/Nitro#3]
I have no idea how to use github and upload files, although I did try uploading a file and it said I don't have access. Anyways, this is a fix for showing player features like color or puffle in game. Replace the joinroom function in Gas.pm with this http://pastebin.com/e1u29Qfb . http://prntscr.com/ej6ilx

**Comment by titshacking** [comment]
Thanks for your contribution, kindly however avoid using pastebin and instead use [Gists ](https://gist.github.com/). If you want to contribute, fork off the repository and create pull requests from here on and I'll approve of it, if it works. I've applied the fix: https://github.com/titshacking/Nitro/commit/e4276325b9024fbe0ab99b3279b45a1254a6f54d
