### ISSUE TITLE
Usernames with spaces are not accepted?

### ISSUE THREAD

**Issue by tootyta** [titshacking/Nitro#5]
So I remember an old Luna issue where you it will give you the Penguin not Found? Error if you register and try to login with a username that has a space in it. Here is the log and stuff http://prntscr.com/ejko01 , and here http://prntscr.com/ejkoam is the DB info.

**Comment by titshacking** [comment]
I've said this over and over again, and I'm sure you know why I've disabled it on Luna as well. **_Security_**.

**Comment by tootyta** [comment]
Oh, alright. Sorry :(
